### ISSUE TITLE
db.n3.put hangs

### ISSUE THREAD

**Issue by zepheiryan** [mcollina/levelgraph-n3#16]
I'd like to use levelgraph for a project that involves receiving and storing triples for search, but it seems like the `put` call for levelgraph-n3 is hanging.  The triples are indeed stored as a subsequent search shows, but there's no apparent call on the continuation `putResult` below - "running?" is never output, and, in this usage, the HTTP PUT that kicks it off spins until it times out because `res.send` is also never called.

```javascript
server.put('/resource/new', function newResource(req, res, next) {
    db.n3.put(req.body.n3, function putResult(err) {
        console.log('running?');
        if (typeof err === "undefined" || err === null) {
            res.send(201, {'success': true});
        } else {
            console.log(err);
            res.send(500, {'success': false});
        }
    });
    return next();
});
```

Am I using it wrong?

* node: 0.10.x, 0.12.4
* levelgraph-n3: 0.5.0
* levelgraph: 0.10.5
* level: 1.0.0

This also kicks out a Node warning about possible leaking due to too many listeners:

```
(node) warning: possible EventEmitter memory leak detected. 16 _drain listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Stream.addListener (events.js:179:15)
    at Stream.once (events.js:204:8)
    at write (.../lib/node_modules/levelgraph/node_modules/level-write-stream/index.js:22:20)
    at Stream.EndStream.ended (.../lib/node_modules/levelgraph/node_modules/level-write-stream/node_modules/end-stream/index.js:13:9)
    at Stream.handleWrite [as write] .../lib/node_modules/levelgraph/node_modules/level-write-stream/node_modules/end-stream/node_modules/write-stream/index.js:22:28)
    at write (.../lib/node_modules/levelgraph/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (.../lib/node_modules/levelgraph/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at .../lib/node_modules/levelgraph/node_modules/readable-stream/lib/_stream_readable.js:600:7
    at process._tickDomainCallback (node.js:381:11)
```

though I've hackishly modified the EventEmitter prototype to increase the limit, and when it's high enough so this warning doesn't show, the `put` call still hangs.

**Comment by mcollina** [comment]
Currently you should use level < 1.

**Comment by zepheiryan** [comment]
That works, thanks!

**Comment by mcollina** [comment]
Can you please try with version 1.0.0? That should work with level > 1.0.0.
