### ISSUE TITLE
Supporting formulas and quantification

### ISSUE THREAD

**Issue by SergioML9** [mcollina/levelgraph-n3#19]
Hi,

I'm trying to use levelgraph-n3 for storing N3 rules, but I need they have formulas and quantification like this example: http://n3.restdesc.org/rules/
If I write a simple rule like this:

@prefix ppl: <http://example.org/people#>.
@prefix foaf: <http://xmlns.com/foaf/0.1/>.

{
    ppl:Cindy foaf:knows ppl:John.
}
=>
{
    ppl:John foaf:knows ppl:Cindy.
}.

I get a syntax error in '=>'. Is there any way to store rules with this format using levelgraph-n3?

Thank you very much !

**Comment by mcollina** [comment]
Levelgraph does not support automatic reasoning, it would be a super nice feature to add on top of it!!
Would you like to contribute?
