### ISSUE TITLE
CLI for importing a dataset

### ISSUE THREAD

**Issue by mcollina** [mcollina/levelgraph-n3#9]
I think a good tool we are missing is a CLI that loads an n3 file in LevelGraph-N3, ideally with a progress bar.

**Comment by transcranial** [comment]
Hey, I made this very simple CLI tool for one of my projects: [levelgraph-n3-import](https://github.com/transcranial/levelgraph-n3-import)

**Comment by mcollina** [comment]
Would you like to have that merged in this project? I will also add you as a maintainer!

**Comment by transcranial** [comment]
Awesome. I'd like to write something for levelgraph-jsonld as well. I'll send pull requests.

**Comment by mcollina** [comment]
Great!! :)
